#!/bin/bash

scontrol_show_nodes  \
	| awk '\
	BEGIN{CONVFMT = "%2.0f";ymax=1} \
	($1 ~ /^c[0-9]+/){x=substr($1,5,1); y=substr($1,3,2); cpu=$2; mem=($6-$7)/1000; grid["cpu"][x+0][y+0]=cpu; grid["mem"][x+0][y+0]=mem;if(y+0>ymax){ymax=y+0}}\
	END{
		print "-------- CORES ALLOC --------";for(y=0; y<= ymax; y++){for(x=0;x<10; x++){printf grid["cpu"][x][y+0]"\t"};printf "c["y"0-"y"9]\n"};\
		print "-------- MEM   AVAIL --------";for(y=0; y<= ymax; y++){for(x=0;x<10; x++){printf grid["mem"][x][y+0]"\t"};printf "c["y"0-"y"9]\n"};
	}' \
	| grep -C 100 --color -w 0
