#!/bin/bash
LONG_NAME="%.18i %.9P %.80j %.8u %.2t %.10M %.6D %R"
if [[ "$*" = *-o* || "$*" = *-l* ]]; then 
	exec squeue -u $USER $*
else
	echo with long names
	exec squeue -u $USER -o "$LONG_NAME" $*
fi

