#!/bin/bash
#
# email me when qstat shows no jobs for me
#
# set up notification for individual jobs - if you want
# qalter -M $USER@uab.edu -m eas
#
SLEEP=60
FILTER=.
if [ "$1" == "-n" ]; then SLEEP="$2"; echo SLEEP=$SLEEP; shift 2; fi
if [ -n "$1" ]; then FILTER="$1"; echo FILTER=$FILTER; shift; fi
EMAILS=$USER@uab.edu
while [[ "$1" == *@* ]]; do 
	EMAILS="$EMAILS $1"
	shift
done
echo "EMAILS=$EMAILS"
MESSAGE=done
if [ -n "$2" ]; then MESSAGE="$*"; fi

count_jobs() {
	# %80j means 1st 80 characters of job name
	JOB_COUNT=`squeue  -h --format "%80j" -u $USER | egrep -c -e "$FILTER"`
}
count_jobs
while [ "$JOB_COUNT" -gt 0 ]; do
	echo -n "$JOB_COUNT '$FILTER' jobs running @ " ; date
	# wait 30 seconds before checking again
        sleep $SLEEP
	count_jobs
done
# email final status
(echo "cheaha queue done";echo "FILTER: $FILTER"; echo "MESSAGE: $MESSAGE") | mail -s "qstat: cheaha all done $FILTER" $EMAILS
echo "email sent to $EMAILS"

