#!/bin/bash
KILL=
if [[ "$1" == "-k" || "$1" == "-d" ]]; then
    KILL=yes
    shift 1
fi

# show list
qstat | grep -e "$1" | perl -pe 's/ +/\t/g;' | cut -f 1,3,5

# kill them
if [ -n "$KILL" ]; then
    qstat | grep -e "$1" | cut -d " " -f 1 | xargs qdel 
fi

