#!/bin/bash
NO_KILL=echo
if [[ "$1" == "-k" || "$1" == "-d" ]]; then
    NO_KILL=
    shift 1
fi

# show list
qstat | grep -e "$1" |  awk '(NR!=2){print $1,$5,$4,$3}'| column -t

# kill them
qstat | grep -e "$1" | awk '(NR>2){print $1}' | xargs $NO_KILL qdel 
echo "LISTING ONLY: re-run with -k or -d to actually kill the jobs"


