#!/bin/bash
#
# email me when qstat shows no jobs for me
#
# set up notification for individual jobs - if you want
# qalter -M $USER@uab.edu -m eas
#
FILTER=.
if [ -n "$1" ]; then FILTER="$1"; shift; fi
EMAILS=$USER@uab.edu
while [[ "$1" == *@* ]]; do 
	EMAILS="$EMAILS $1"
	shift
done
echo "EMAILS=$EMAILS"
MESSAGE=done
if [ -n "$2" ]; then MESSAGE="$*"; fi

JOB_COUNT=`qstat -u $USER |  grep -e "$FILTER" | wc -l`
echo -n "$JOB_COUNT '$FILTER' jobs running @ " ; date
while [ "$JOB_COUNT" -gt 0 ]; do
	echo -n "$JOB_COUNT '$FILTER' jobs running @ " ; date
	# wait 30 seconds before checking again
        sleep 60
	JOB_COUNT=`qstat -u $USER | grep -e "$FILTER" | wc -l`
done
# email final status
(echo "cheaha queue done";echo "FILTER: $FILTER"; echo "MESSAGE: $MESSAGE") | mail -s "qstat: cheaha all done $FILTER" $EMAILS
echo "email sent to $EMAILS"

