#!/bin/bash
if [ "$1" == "-f" ]; then FACL=1; shift ; fi
T=$(pwd -LP)
if [ ! -z "$1" ]; then T=$1; fi
if [ -z "$FACL" ]; then
	# raw ls-ls version
	(while [ "$T" != '/' ]; do
		# simple LS
		ls -lsd $T
		T=$(dirname $T)
	done) | column -t 
else
	# getfacl version
	while [ "$T" != '/' ]; do
		echo "#### $T ####"
		getfacl $T
		T=$(dirname $T)
	done
fi

